/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.protonstandalonegui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pcdebian
 */
public class FrmMain extends javax.swing.JFrame {

    private String nombrearchivo;
    private String rutaproton = "";
    private String rutawine = "";
    private String rutajuego;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();

        File f = new File("protonpath.txt");
        if (f.exists() && f.isFile()) {

            try {
                BufferedReader br = new BufferedReader(new FileReader("protonpath.txt"));
                rutaproton = br.readLine();
                tprotonpath.setText(rutaproton);
                br.close();
            } catch (IOException ex) {

            }
        }

        f = new File("winepath.txt");
        if (f.exists() && f.isFile()) {

            try {
                BufferedReader br = new BufferedReader(new FileReader("winepath.txt"));
                rutawine = br.readLine();
                twinepath.setText(rutawine);
                br.close();
            } catch (IOException ex) {
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        truta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bcancelar = new javax.swing.JButton();
        baceptar = new javax.swing.JButton();
        barchivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tprotonpath = new javax.swing.JTextField();
        twinepath = new javax.swing.JTextField();
        bprotonpath = new javax.swing.JButton();
        bwinepath = new javax.swing.JButton();
        cLibraries = new javax.swing.JComboBox<>();
        cVrGame = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Game exe");

        bcancelar.setText("Exit");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        baceptar.setText("Create sh");
        baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baceptarActionPerformed(evt);
            }
        });

        barchivo.setText("...");
        barchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Proton path");

        jLabel3.setText("Wine path");

        bprotonpath.setText("...");
        bprotonpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprotonpathActionPerformed(evt);
            }
        });

        bwinepath.setText("...");
        bwinepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwinepathActionPerformed(evt);
            }
        });

        cLibraries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Steam Libraries", "System Libraries" }));

        cVrGame.setText("VR Game WiVRN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(truta, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tprotonpath)
                            .addComponent(twinepath))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(bprotonpath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bwinepath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(bcancelar)
                .addGap(48, 48, 48)
                .addComponent(baceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cVrGame)
                    .addComponent(cLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tprotonpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bprotonpath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bwinepath))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(twinepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(truta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barchivo))
                .addGap(18, 18, 18)
                .addComponent(cLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bcancelar)
                            .addComponent(baceptar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cVrGame)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchivoActionPerformed
        // TODO add your handling code here:
        //Handle open button action.
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "EXE", "exe", "EXE");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            truta.setText(chooser.getSelectedFile().getAbsolutePath());
            nombrearchivo = chooser.getSelectedFile().getName();
            rutajuego = chooser.getSelectedFile().getParent();

        }

    }//GEN-LAST:event_barchivoActionPerformed

    private void baceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baceptarActionPerformed
        rutaproton = tprotonpath.getText();
        rutawine = twinepath.getText();
        String libraries;
        if (cLibraries.getSelectedIndex() == 1) {
            libraries = "export LD_LIBRARY_PATH=\"/usr/lib64/wine:/usr/lib32/wine:/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu\"";
        } else {
            libraries = "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/pinned_libs_32:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib64/qt-3.3/lib:/usr/lib64/tcl8.6:/usr/lib/wine:/usr/lib64/wine:/lib:/lib64:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/lib:/home/$USER/$STEAM_HOME_DIR/ubuntu12_32/steam-runtime/usr/lib:\"\n";
        }
        String vrgame;
        if(cVrGame.isSelected())
        {
            vrgame="PRESSURE_VESSEL_IMPORT_OPENXR_1_RUNTIMES=1 ";
        }
        else
        {
            vrgame="";
        }
        if (!rutajuego.isEmpty() && !nombrearchivo.isEmpty() && !rutaproton.isEmpty() && !rutawine.isEmpty()) {
            try {
                // TODO add your handling code here:
                FileWriter myWriter = new FileWriter(rutaproton + "/" + Metodos.quitaextension(nombrearchivo) + ".sh");
                myWriter.write("PROTON=$PWD/proton\n"
                        + "\n"
                        + "# Uncomment these options as required. Note: DXVK / D9VK is enabled by default and does not need any of the\n"
                        + "# options below\n"
                        + "\n"
                        + "#export DXVK_LOG_LEVEL=\"info\"\n"
                        + "#export PROTON_USE_WINED3D=\"1\"\n"
                        + "#export PROTON_USE_WINED3D11=\"1\"\n"
                        + "#export PROTON_NO_D3D11=\"1\"\n"
                        + "#export PROTON_NO_D3D10=\"1\"\n"
                        + "#export PROTON_NO_D9VK=\"1\"\n"
                        + "#export PROTON_NO_ESYNC=\"1\"\n"
                        + "#export PROTON_USE_VKD3D=\"1\"       #<-----DX12 support (only for versions of proton built with DX12 support)\n"
                        + "#export PROTON_NO_FSYNC=\"1\"\n"
                        + "#export PROTON_FORCE_LARGE_ADDRESS_AWARE=\"1\"\n"
                        + "#export PROTON_OLD_GL_STRING=\"1\"\n"
                        + "\n"
                        + "if [ -d \"$HOME/.steam/steam/ubuntu12_32/steam-runtime\" ]; then\n"
                        + "    STEAM_HOME_DIR=\".steam/steam\"\n"
                        + "    echo \"Using Steam directory: $HOME/$STEAM_HOME_DIR\"\n"
                        + "elif [ -d \"$HOME/.steam/debian-installation/ubuntu12_32/steam-runtime\" ]; then\n"
                        + "    STEAM_HOME_DIR=\".steam/debian-installation\"\n"
                        + "    echo \"Using Steam directory: $HOME/$STEAM_HOME_DIR\"\n"
                        + "elif [ -d \"$HOME/.local/share/Steam/ubuntu12_32/steam-runtime\" ]; then\n"
                        + "    STEAM_HOME_DIR=\".local/share/Steam\"\n"
                        + "    echo \"Using Steam directory: $HOME/$STEAM_HOME_DIR\"\n"
                        + "else\n"
                        + "    echo \"Steam runtime not found\"\n"
                        + "    exit 1\n"
                        + "fi"
                        + "\n"
                        + "#These 4 exports are NOT required for Joypad support but they are set by Steam so there is no harm in having them set here\n"
                        + "export SDL_GAMECONTROLLERCONFIG=\"03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,03000000de280000fc11000001000000,Steam Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,030000005e040000a102000007010000,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,0000000058626f782047616d65706100,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,030000005e0400008e02000010010000,X360 Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,\"\n"
                        + "export SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD=\"1\"\n"
                        + "export SDL_GAMECONTROLLER_USE_BUTTON_LABELS=\"1\"\n"
                        + "export SDL_VIDEO_X11_DGAMOUSE=\"0\"\n"
                        + libraries +"\n"
                        + "export STEAM_COMPAT_DATA_PATH=\"" + rutawine + "\"\n"
                        + "cd \"" + rutajuego + "\"\n"
                        + vrgame + "python3 $PROTON waitforexitandrun \"" + nombrearchivo + "\" \"-d3d12 -FullscreenMode=1 -Fullscreen\""
                );
                myWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You need to fill all fields.");
        }


    }//GEN-LAST:event_baceptarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bprotonpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprotonpathActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);
        tprotonpath.setText(f.getSelectedFile().getAbsolutePath());
        try {
            FileWriter myWriter = new FileWriter("protonpath.txt");
            myWriter.write(tprotonpath.getText());
            myWriter.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_bprotonpathActionPerformed

    private void bwinepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwinepathActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);
        twinepath.setText(f.getSelectedFile().getAbsolutePath());
        try {
            FileWriter myWriter = new FileWriter("winepath.txt");
            myWriter.write(twinepath.getText());
            myWriter.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_bwinepathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baceptar;
    private javax.swing.JButton barchivo;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bprotonpath;
    private javax.swing.JButton bwinepath;
    private javax.swing.JComboBox<String> cLibraries;
    private javax.swing.JCheckBox cVrGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tprotonpath;
    private javax.swing.JTextField truta;
    private javax.swing.JTextField twinepath;
    // End of variables declaration//GEN-END:variables
}
